# Generated by Django 4.0.6 on 2023-01-11 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_shippinglprice_order_shippingprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postalcode',
            new_name='postalCode',
        ),
    ]
