# Generated by Django 4.0.6 on 2023-01-11 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_shippingaddress_shippingprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='ShippingPrice',
            new_name='shippingPrice',
        ),
    ]
