# Generated by Django 4.0.6 on 2023-01-11 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_shippingprice_shippingaddress_shippingprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippinglPrice',
            new_name='shippingPrice',
        ),
    ]
